name: "Social Impact Marketing Request"
description: "Request new initiatives to be included in the Social Impact editorial calendar and be featured on various GitHub platforms"
title: "Marketing Request"
labels:
  - "TYPE: Marketing Request"
assignees:
  - "@camaleyjennings1"
  - "@hanamarino"
  - "@abbitude"

welcome:
  label: "Welcome!"
  value: |
    If you’ve made it here, that means you probably have a new, exciting social impact initiative that you’re working on - congrats! Now it’s time to get the word out. We’re here to highlight all of the important work you’re doing by helping craft narratives and coordinating it within the greater Social Impact Editorial Calendar. Below, you’ll find the timeline for what will happen next, as well as a guide to help collect all necessary information regarding your initiative. For more information on how much planning time each marketing channel requires, please view our [Marketing Channels Guide](https://github.com/github/social-impact/wiki/GitHub-&-MSFT-Marketing-Channels-Guide)"

timeline_checklist:
  label: "Timeline & Checklist"
  description: "Timeline for the marketing process"
  options:
    - "Owner submits issue (minimum 6 weeks before launch)"
    - "SI Team reviews request in accordance with marketing calendar (reviewed 1x per week)"
    - "Marketing plan shared with owner for feedback"
    - "Stories are written, assets are created, and your story goes live across platforms!"

directlyresponsible_individual:
  label: "DRI(s) GitHub handle(s)"

key_storyline:
  label: "Story/Event Overview"
  description: "An overview of the story you’d like us to tell"

internally_externally:
  label: "Should this be marketed internally or externally?"
  options:
    - "Internally"
    - "Externally"

platforms:
  label: "Platforms: Where do you envision this being published?"
  options:
    - "Hub post"
    - "GitHub LinkedIn"
    - "GitHub X"
    - "SI Website"
    - "SI Insights Perspectives Post"
    - "GitHub.blog"
    - "Conference"
    - "Other (please elaborate)"

tentative_date:
  label: "Tentative Date"
  description: "Is this a series or should it be launched on a specific day?"

key_audience:
  label: "Key Audience & Geo"
  description: "Is this meant for developers, social impact orgs, or some other particular sector?"

program_areas:
  label: "What program areas does the story cover?"
  options:
    - "Skilling"
    - "Environmental Sustainability"
    - "Accessibility"
    - "Humanitarian Response"
    - "Employees"
    - "Developers"
    - "Nonprofits"

budget:
  label: "Do you have budget?"
  description: "If you have budget for this, please specify."

relevant_links:
  label: "Links to any relevant Issues, docs, photos etc."
  description: "Links related to the initiative"

goal:
  label: "What is your goal?"
  description: "What is the desired outcome of this initiative?"
